import { createClient } from '@supabase/supabase-js';
import { NextResponse } from 'next/server';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req) {
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return NextResponse.json({ error: 'Server misconfiguration' }, { status: 500 });
  }

  const supabaseAdmin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    { auth: { autoRefreshToken: false, persistSession: false } }
  );

  try {
    const { email, pantryId, role, pantryName, joinCode } = await req.json();

    // 1. Try to Generate a "New User" Invite Link
    let inviteLink = null;
    
    const { data: linkData, error: linkError } = await supabaseAdmin.auth.admin.generateLink({
      type: 'invite',
      email: email,
      options: {
        redirectTo: `${process.env.NEXT_PUBLIC_SITE_URL}/onboarding`,
        data: { invited_to_pantry: pantryId, role: role || 'volunteer' }
      }
    });

    if (linkError) {
      // HANDLE EXISTING USER SCENARIO
      if (linkError.code === 'email_exists' || linkError.message.includes('already registered')) {
        console.log("ℹ️ User already exists. Sending standard login link.");
        // If they exist, sending them to /onboarding with the code will let the wizard 
        // automatically detect they are logged in and just ask them to "Join Team"
        inviteLink = `${process.env.NEXT_PUBLIC_SITE_URL}/onboarding?code=${joinCode}`;
      } else {
        console.error("Link Gen Error:", linkError);
        return NextResponse.json({ error: linkError.message }, { status: 400 });
      }
    } else {
      // If new user, use the Magic Link generated by Supabase
      // We append the code so the wizard pre-fills it
      inviteLink = `${linkData.properties.action_link}&code=${joinCode}`;
    }

    // 2. Send the Email (Resend)
    // 👇 UPDATED: Changed 'from' to your real domain
    const { data: emailData, error: emailError } = await resend.emails.send({
      from: 'Food Arca <invites@foodarca.com>', 
      to: email, 
      subject: `You've been invited to join ${pantryName}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
          <h2>Join ${pantryName} on Food Arca</h2>
          <p>You have been invited to join the team as a <strong>${role}</strong>.</p>
          
          <div style="background: #f9f9f9; padding: 15px; border-radius: 8px; margin: 20px 0; text-align: center;">
            <p style="margin: 0 0 10px; color: #666;">Your Organization Join Code:</p>
            <code style="font-size: 24px; font-weight: bold; letter-spacing: 2px;">${joinCode}</code>
          </div>

          <p>Click the button below to accept the invite:</p>
          
          <a href="${inviteLink}" style="display: inline-block; background: #d97757; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold;">
            Accept Invitation
          </a>

          <p style="margin-top: 30px; font-size: 12px; color: #888;">
            If the button doesn't work, login at foodarca.com/onboarding and enter code: ${joinCode}
          </p>
        </div>
      `
    });

    if (emailError) {
      console.error("Resend Error:", emailError);
      return NextResponse.json({ error: "Failed to send email" }, { status: 500 });
    }

    return NextResponse.json({ success: true });

  } catch (err) {
    console.error("API Crash:", err);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}